version: '3.7'

services:
  web:
    build: ./poker_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./poker_app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=poker
      - POSTGRES_PASSWORD=poker
      - POSTGRES_DB=poker

volumes:
  postgres_data: